### Запрос на добавление машин
POST http://localhost:8080/add_cars
Content-Type: application/json

{
  "regNums": [
    "А444АА123"
  ]
}

### Запрос на изменение данных машины
POST http://localhost:8080/modify_car?reg_num=А444АА123
Content-Type: application/json

{
  "Mark": "Lada"
}

### Запрос на получение данных машины
GET http://localhost:8080/get_cars?model=Vesta

### Запрос на удаление машины
DELETE http://localhost:8080/delete_car?regNum=К123XX123
